project:
  type: website

website:
  title: "Project by Toros-Manuk"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Sources
        menu:
          - href: source-1.qmd
            text: WhoScored
          - href: source-2.qmd
            text: SofaScored 
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



