project:
  type: website

website:
  title: "Toros-Manuk's project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Data Analysis
      - text: Sources
        menu:
          - href: source-1.qmd
            text: WhoScored
          - href: source-2.qmd
            text: SofaScore 
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



